DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;

DROP TABLE ANSWERBOARD;

--글 번호 시퀀스 (PRIMARY KEY)
CREATE SEQUENCE BOARDNOSQ;

--그룹 번호 시퀀스(새로운 글 등록할 때만)
CREATE SEQUENCE GROUPNOSQ;

--글 번호, 그룹 번호, 그룹 순서, 제목 탭, 제목, 내용, 작성자 , 작성일
CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL,
	ISDEL VARCHAR2(10) NOT NULL
	CONSTRAINT ISDEL_CHK CHECK(ISDEL IN('Y','N')),
	PARENTNO NUMBER 
);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

INSERT INTO ANSWERBOARD VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL,1,0,
'첫번째 글', '1번 글 입니다.','유저1',SYSDATE,'N',1);

--두번째 글 작성
INSERT INTO ANSWERBOARD VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL,1,0,
'두번째 글', '2번 글 입니다','유저2', SYSDATE, 'N',2);

--답글 작성 (1번 글에)
--부모와 같은 GROUPNO
--부모의 GROUPSQ+1, 부모의 TITLETAB+1
INSERT INTO ANSWERBOARD VALUES(BOARDNOSQ.NEXTVAL,(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+1,
 'RE:첫번째 글', '1번 글에 답글입니다.', '유저2',SYSDATE,'N',1);
 
 --세번째 글 작성
 INSERT INTO ANSWERBOARD 
 VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL,1,0,'세번째 글','3번 글 입니다.', '유저3', SYSDATE);
 
 --답글 작성(두번째 글에)
 INSERT INTO ANSWERBOARD 
 VALUES(BOARDNOSQ.NEXTVAL, 
 (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
 (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
 (SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
 'RE:두번째 글', '2번 글에 답글입니다.(1)', '유저1',SYSDATE,'N', 2);
 
 --답글 작성(RE:두번째 글 - 5)
 --부모와 같은 GROUPNO
 --부모의 GROUPSQ+1, 부모의 TITLETAB+1
 INSERT INTO ANSWERBOARD
 VALUES(BOARDNOSQ.NEXTVAL,
 (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
  (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
   (SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
 'RE:RE:두번째 글', '2번 글 답글에 답글입니다.(1)', '유저2',SYSDATE);
 
 
 --답글 작성 (두번째 글 - 2)
 
 --부모와 같은 GROUPNO에서
 --부모의 GROUPSQ보다 큰 글들의 GROUPSQ+1
 UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
 WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD
 				  WHERE BOARDNO=2) AND
 	   GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD
 	   			  WHERE BOARDNO=2);
 
 INSERT INTO ANSWERBOARD
 VALUES(BOARDNOSQ.NEXTVAL,
 (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
  (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
   (SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
 'RE:두번째 글', '2번 글에 답글입니다.', '유저2', SYSDATE);
 
 UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
 WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD
 				  WHERE BOARDNO=2) AND
 	   GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD
 	   			  WHERE BOARDNO=2);
 	   			  
 INSERT INTO ANSWERBOARD
 VALUES(BOARDNOSQ.NEXTVAL,
 (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
  (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
   (SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
 'RE:두번째 글', '2번 글에 답글입니다.', '유저2', SYSDATE);
 	   			  
 
 UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
 WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD
 				  WHERE BOARDNO=7) AND
 	   GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD
 	   			  WHERE BOARDNO=7);
 
 INSERT INTO ANSWERBOARD
 VALUES(BOARDNOSQ.NEXTVAL,
 (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7),
  (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
   (SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+1,
 'RE:두번째 글', '2번 답글에 답글입니다.', '유저2', SYSDATE);
 
 
 
 DROP TABLE MYMEMBER;
 DROP SEQUENCE MYNOSEQ;
 
 CREATE SEQUENCE MYNOSEQ;
 
 --멤버번호, 아이디, 비밀번호, 이름, 주소, 전화번호
 --이메일, 가입여부(가입/탈퇴), 등급(ADMIN, USER,..)
 CREATE TABLE MYMEMBER(
 	MYNO NUMBER NOT NULL,
 	MYID VARCHAR2(500) NOT NULL,
 	MYPW VARCHAR2(500) NOT NULL,
 	MYNAME VARCHAR2(1000) NOT NULL,
 	MYADDR VARCHAR2(4000) NOT NULL,
 	MYPHONE VARCHAR2(20) NOT NULL,
 	MYEMAIL VARCHAR2(100) NOT NULL,
 	MYENABLED VARCHAR2(2) NOT NULL,
 	MYROLE VARCHAR2(50) NOT NULL,
 	CONSTRAINT MYMEMBER_PK PRIMARY KEY(MYNO),
 	CONSTRAINT MYMEMBER_UQ_ID UNIQUE(MYID),
 	CONSTRAINT MYMEMBER_UQ_PHONE UNIQUE(MYPHONE),
 	CONSTRAINT MYMEMBER_UQ_EMAIL UNIQUE(MYEMAIL),
 	CONSTRAINT MYMEMBER_ENABLED_CHK CHECK(MYENABLED IN('Y', 'N'))
 );
 
 INSERT INTO MYMEMBER
 VALUES(MYNOSEQ.NEXTVAL, 'HONG', 'HONG1234', '관리자', '관리시 관리구 관리동', '010-1234-1234',
 'HONG@MYMEMBER.COM', 'Y', 'ADMIN');
 
 	   			  
 	   			  